[tox]
envlist = py310, py311, py312, py313
isolated_build = True

[testenv]
deps =
    pytest>=7.0.0
    pytest-cov>=4.0.0
commands =
    pytest {posargs:tests}

[flake8]
max-line-length = 150
ignore = E501, W503
exclude = .tox,*.egg,build,data,venv,.venv
