# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data ingestion
      run: |
        python src/data_ingestion/data_ingestion.py

    - name: Run data preprocessing
      run: |
        python src/data_preprocessing/data_preprocessing.py
        # python src/data_preprocessing/data_preprocessing.py --input_data /path/to/ingested_data.csv --train_data /path/to/preprocessed_data.npy --test_data /path/to/test_data.npy

    - name: Train models
      run: |
        python src/model_training/train_models.py
        # python src/model_training/train_models.py --preprocessed_data /path/to/preprocessed_data.npy --output_dir /path/to/models/

    - name: Evaluate models
      run: |
        python src/model_evaluation/evaluation.py
        # python src/model_evaluation/evaluation.py --model_path /path/to/trained_model.pkl --test_data /path/to/test_data.npy --output_path /path/to/evaluation_report.csv

    - name: Package project
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with Flake8
      run: |
        flake8 .

  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm install --global prettier

    - name: Run Prettier
      run: |
        prettier --check . || true

  deploy:
    needs: [build, lint, prettier]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download package artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Deploy to production
      run: |
        # Add your deployment steps here
        # For example, you can use a package repository or a deployment service
        # to deploy the FraudShield package to your production environment